#!/bin/bash
#
# $Id: build_bkls.sh 579 2010-04-16 14:48:40Z tfonrouge $
#

aMainDirs="demos samples tests"

formats='gnu msvc mingw borland watcom'

empty_str=""

if [ `uname` == "Darwin" ] ; then
  SEDCMD="sed -i .bak"
else
  SEDCMD="sed -i"
fi

echo "Building makefiles for wxHarbour library"

for fmt in $formats ; do
  bakefile -f $fmt -D FORMAT_HAS_MAKE_INSTALL=1 wxharbour.bkl
done

for mainDir in $aMainDirs ; do

  adirs="$(find $mainDir -maxdepth 1 -mindepth 1 -type d \! -name .svn)"

  echo "Building makefiles for $mainDir"

  for DIR in $adirs ; do

    ndir=${DIR/$mainDir\//}
    cp config/hbmk.hbm $mainDir/$ndir/
    sed -i "s/\$Id:.*\$/autogenerated/" "$mainDir/$ndir/hbmk.hbm"
    cp config/mkdirstempl.bkl $mainDir/$ndir/$ndir.bkl
    SEAREP=s/__SAMPLE_NAME__/$ndir/
    $SEDCMD $SEAREP $mainDir/$ndir/$ndir.bkl
    if [ -e $mainDir/$ndir/$ndir.bkl.bak ] ; then rm $mainDir/$ndir/$ndir.bkl.bak ; fi

    for fmt in $formats ; do
      bakefile -f $fmt $mainDir/$ndir/$ndir.bkl -DFORMAT_HAS_MAKE_INSTALL=1
    done

  done

done
